---
stages:
- name: Build
  inputs:
  - type: git
    branch: develop
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: carbon-website/dist
    build_type: shell
    script: "#!/bin/bash\nshopt -s extglob\n\nNODE_VERSION=\"v5.4.1\"\n\nfunction\
      \ update_node_js() {\n\tlocal VERSION=$1\n\tif [[ -z $VERSION ]]; then\n\t\t\
      echo \"${red}Expected version number to be passed into update_node_js\"\n\t\t\
      return 1;\n\tfi\n\n\tlocal CURRENT_DIRECTORY=`pwd`\n\tmkdir ~/local\n\tcd ~/local\n\
      \techo \"Downloading NodeJS $VERSION\"\n\tcurl http://nodejs.org/dist/$VERSION/node-$VERSION-linux-x64.tar.gz\
      \ | tar xz --strip-components=1\n\n\texport PATH=$HOME/local/bin:$PATH\n\n\t\
      cd $CURRENT_DIRECTORY\n\t\n\techo \"NodeJS updated to $VERSION\"\n}\n\nmkdir\
      \ carbon-website\n\necho \"Moving all files into carbon-website folder\"\nmv\
      \ !(carbon-website) .[^.]* carbon-website\n\nupdate_node_js $NODE_VERSION\n\n\
      git clone https://CarbonDeployer:N6c7ZluGejBy@github.com/CarbonLDP/CarbonLDP-JS-SDK.git\n\
      \ncd carbon-website\n\nmkdir -p $ARCHIVE_DIR\n\nBUILD_VERSION=`node -e \"console.log(require('./package.json').version);\"\
      `\necho \"BUILD_VERSION=$BUILD_VERSION\" >> dist/build.properties\n\nCONTAINER_NAME=\"\
      website$RANDOM\"\necho \"CONTAINER_NAME=$CONTAINER_NAME\" >> dist/build.properties\n\
      \ncat dist/build.properties\n\ncp package.json dist\n\necho \"Installing Node\
      \ dependencies...\"\nnpm install\necho \"Node dependencies installed.\"\n\n\
      echo \"Building project...\"\nnode_modules/.bin/gulp build --profile dev"
- name: Containerize
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Containerize
    type: builder
    extension_id: ibm.devops.services.pipeline.container.builder
    target:
      url: https://api.ng.bluemix.net
      organization: admin@carbonldp.com
      space: dev
    IMAGE_NAME: carbon-website
    USE_CACHED_LAYERS: 'true'
    COMMAND: |-
      #!/bin/bash

      ls -l

      source build.properties

      ice_build_image true registry.ng.bluemix.net/carbonldp/carbon-website:$BUILD_VERSION .
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: builder
    extension_id: ibm.devops.services.pipeline.container.builder
    target:
      url: https://api.ng.bluemix.net
      organization: admin@carbonldp.com
      space: dev
    IMAGE_NAME: carbon-website
    USE_CACHED_LAYERS: 'true'
    COMMAND: "#!/bin/bash\n\nset -a\n. build.properties\n\nNODE_VERSION=\"v5.4.1\"\
      \n\nfunction update_node_js() {\n\tlocal VERSION=$1\n\tif [[ -z $VERSION ]];\
      \ then\n\t\techo \"${red}Expected version number to be passed into update_node_js\"\
      \n\t\treturn 1;\n\tfi\n\n\tlocal CURRENT_DIRECTORY=`pwd`\n\tmkdir ~/local\n\t\
      cd ~/local\n\techo \"Downloading NodeJS $VERSION\"\n\tcurl http://nodejs.org/dist/$VERSION/node-$VERSION-linux-x64.tar.gz\
      \ | tar xz --strip-components=1\n\n\texport PATH=$HOME/local/bin:$PATH\n\n\t\
      cd $CURRENT_DIRECTORY\n\t\n\techo \"NodeJS updated to $VERSION\"\n}\n\nupdate_node_js\
      \ $NODE_VERSION\n\nWORKING_DIRECTORY=`pwd`\n\ngit clone https://CarbonDeployer:N6c7ZluGejBy@github.com/CarbonLDP/carbon-dev.git\n\
      \ncd carbon-dev/devOps\n\necho \"Installing carbon-dev/devOps npm packages...\"\
      \nnpm install\necho \"Dependencies installed\"\n\nnode website/deploy.js --dir=$WORKING_DIRECTORY"
- name: Link HTTP
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Build
    type: builder
    extension_id: ibm.devops.services.pipeline.container.builder
    target:
      url: https://api.ng.bluemix.net
      organization: admin@carbonldp.com
      space: dev
    USE_CACHED_LAYERS: 'true'
    COMMAND: "#!/bin/bash\n\nsource build.properties\n\nNODE_VERSION=\"v5.4.1\"\n\n\
      function update_node_js() {\n\tlocal VERSION=$1\n\tif [[ -z $VERSION ]]; then\n\
      \t\techo \"${red}Expected version number to be passed into update_node_js\"\n\
      \t\treturn 1;\n\tfi\n\n\tlocal CURRENT_DIRECTORY=`pwd`\n\tmkdir ~/local\n\t\
      cd ~/local\n\techo \"Downloading NodeJS $VERSION\"\n\tcurl http://nodejs.org/dist/$VERSION/node-$VERSION-linux-x64.tar.gz\
      \ | tar xz --strip-components=1\n\n\texport PATH=$HOME/local/bin:$PATH\n\n\t\
      cd $CURRENT_DIRECTORY\n\t\n\techo \"NodeJS updated to $VERSION\"\n}\n\nupdate_node_js\
      \ $NODE_VERSION\n\ngit clone https://CarbonDeployer:N6c7ZluGejBy@github.com/CarbonLDP/carbon-dev.git\n\
      cd carbon-dev/devOps\n\necho \"Installing carbon-dev/devOps npm packages...\"\
      \nnpm install\necho \"Dependencies installed\"\n\nnode http/link.js --website=$CONTAINER_NAME"
- name: Clean
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  properties:
  - name: ADDITIONAL_IMAGE_VERSIONS
    value: '1'
    type: text
  jobs:
  - name: Clean
    type: builder
    extension_id: ibm.devops.services.pipeline.container.builder
    target:
      url: https://api.ng.bluemix.net
      organization: admin@carbonldp.com
      space: dev
    IMAGE_NAME: carbon-website
    USE_CACHED_LAYERS: 'true'
    COMMAND: "#!/bin/bash\n\nset -a\n. build.properties\n\nNODE_VERSION=\"v5.4.1\"\
      \n\nfunction update_node_js() {\n\tlocal VERSION=$1\n\tif [[ -z $VERSION ]];\
      \ then\n\t\techo \"${red}Expected version number to be passed into update_node_js\"\
      \n\t\treturn 1;\n\tfi\n\n\tlocal CURRENT_DIRECTORY=`pwd`\n\tmkdir ~/local\n\t\
      cd ~/local\n\techo \"Downloading NodeJS $VERSION\"\n\tcurl http://nodejs.org/dist/$VERSION/node-$VERSION-linux-x64.tar.gz\
      \ | tar xz --strip-components=1\n\n\texport PATH=$HOME/local/bin:$PATH\n\n\t\
      cd $CURRENT_DIRECTORY\n\t\n\techo \"NodeJS updated to $VERSION\"\n}\n\nupdate_node_js\
      \ $NODE_VERSION\n\nWORKING_DIRECTORY=`pwd`\n\ngit clone https://CarbonDeployer:N6c7ZluGejBy@github.com/CarbonLDP/carbon-dev.git\n\
      \ncd carbon-dev/devOps\n\necho \"Installing carbon-dev/devOps npm packages...\"\
      \nnpm install\necho \"Dependencies installed\"\n\nnode website/clean.js --dir=$WORKING_DIRECTORY"
- name: MyStage
  inputs:
  - type: job
    stage: Build
    job: Build
  jobs:
  - name: Build
    type: builder
    extension_id: ibm.devops.services.pipeline.container.builder
    target:
      url: https://api.ng.bluemix.net
      organization: admin@carbonldp.com
      space: dev
    IMAGE_NAME: carbon-website
    USE_CACHED_LAYERS: 'true'
    COMMAND: |-
      #!/bin/bash
      printenv
